# Generated by Django 4.1 on 2022-10-28 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=4096)),
                ('google_id', models.CharField(max_length=256)),
                ('location', models.CharField(max_length=256)),
                ('child_friendly', models.BooleanField(default=True)),
                ('ticket_price', models.CharField(default='', max_length=256)),
                ('opening_times', models.CharField(default='', max_length=256)),
                ('tags', models.ManyToManyField(related_name='places', to='api.placetag')),
            ],
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('kind', models.IntegerField(choices=[(0, 'Inn'), (1, 'Restaurant')], default=0)),
                ('google_id', models.CharField(default='', max_length=256)),
                ('info', models.CharField(max_length=4096)),
                ('near', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.place')),
            ],
        ),
    ]
