# Generated by Django 4.1 on 2022-09-04 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_placephoto_image_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='tags',
            field=models.ManyToManyField(related_name='places', to='api.placetag'),
        ),
        migrations.AlterField(
            model_name='placephoto',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.place'),
        ),
    ]
