# Generated by Django 4.1 on 2022-09-04 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_place_tags_alter_placephoto_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='price',
        ),
        migrations.AddField(
            model_name='place',
            name='opening_times',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='place',
            name='location',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=1024)),
                ('kind', models.IntegerField(choices=[(0, 'Reguler'), (1, 'VIP')], default=0)),
                ('has_tour_guide', models.BooleanField()),
                ('available', models.BooleanField()),
                ('opening_times', models.CharField(default='', max_length=256)),
                ('price', models.IntegerField(default=0)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.place')),
            ],
        ),
    ]
