# Generated by Django 4.1 on 2022-09-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_place_price_place_opening_times_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='child_friendly',
            field=models.BooleanField(default=True),
        ),
    ]
