# Generated by Django 4.1 on 2022-09-04 08:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_place_child_friendly'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default=datetime.date(2022, 9, 4)),
        ),
        migrations.AddField(
            model_name='user',
            name='nat_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='nationality',
            field=models.CharField(default='-', max_length=256),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.IntegerField(default=0),
        ),
    ]
