# Generated by Django 4.1 on 2022-09-04 08:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_birth_date_user_nat_id_user_nationality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2022, 9, 4, 8, 11, 30, 845310, tzinfo=datetime.timezone.utc)),
        ),
    ]
