# Generated by Django 4.1 on 2022-09-04 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_questions_useranswers_reservation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questions',
            new_name='Question',
        ),
        migrations.RenameModel(
            old_name='UserAnswers',
            new_name='UserAnswer',
        ),
    ]
